site_name: InfluxDB 3.0 Python Client
docs_dir: .
nav:
  - Home: index.md
  - API Reference: api_reference.md
plugins:
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [ ../influxdb_client_3 ]
          options:
            summary: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true